tobiasbp/python-arcade-dungeon

- my_game.py
Added dict _MAP_LAYER_CONFIG_ for controlling how sprites on layers are drawn.
> Add layer config

- my_game.py
- Set a new text pixel font as a global variable called "MAIN_FONT"
- Removed the "Dying after 100 points" function.
> Fonts + Game over functionality

- my_game.py
- my_sprites.py
When the player knows the keys that control it, we can scale up to multiplayer much easier since we don't need to know about the number of players in the main loop.
> Move responsibility of acting on control keys to Player class

- my_sprites.py
Rebased and put in the arcade.load_texture_pair().
> PlayerTurning - After Commits

- my_game.py
- my_sprites.py
Added PlayerTypes. If no type is chosen for a Player, it will have a random type.
> Add player types

- my_game.py
- my_sprites.py
#19 Adding features:
* Enemy roaming stage
* Enemy hp property, with a setter and a getter
* more?
> Add Enemy states chasing and roaming

- my_game.py
- my_sprites.py
- The Enemy now reacts with exclamation_red when they see the player.
- ## NOTICE! Just one question, should the enemies react when they lose the sight of the player?
> Enemy reaction when seeing player

- my_sprites.py
```
I'm really cool
```
*Yeah*
> Added all the emotes to the game

- my_sprites.py
Added weapons 🔪
-----------------------------------------------------------------------------------------------------------------------------------
SWORD_SHORT 
SWORD_LONG
SWORD_FALCHION
SWORD_DOUBLE_SILVER
SWORD_DOUBLE_BRONZE
HAMMER
AXE_DOUBLE
AXE_SINGLE
STAFF_PURPLE
STAFF_GREEN
SPEAR
> - ADDED MOST WEAPONS ⚔️🗡️🔪

- my_game.py
fixed error with wrong variable name in mygame
> fixed error with wrong variable name

- my_game.py
apparentky some paths were written with backslashes. Changed that. Very small PR.
> changed some backslashes to forward slashes

- my_game.py
- Press R to restart the game.
- The Debug Mode have to be on.
> Restart Key! 🔁

- my_game.py
adding the ability to have several players in the game.
> the multiplayer feature

- my_sprites.py
Enemies now work with 2 players on the map.
> Make enemies work with multiplayer

- my_sprites.py
the enemies will now stop when the distance to the player is less than the range of its weapon
> enemies stop its weapons range from the players

- my_game.py
Amazing features in this PR:
* Pressing space on the intro screen does not crash the game,
* Number of players can be chosen by pressing keys 1 or 2 on the intro screen.
> Press keys 1 or 2 to start game.

- my_sprites.py
Changes in this _PR_:
* Lifebars can now go to 0. 
* Lifebars are only updated when _Entities'_ healt changes.
> Fix: Lifebar can not go to 0

- my_game.py
- my_sprites.py
now, the weapons' attack points align with the waepon position during an attack.
> Fix attack point positions

- my_game.py
- my_helpers.py
- my_sprites.py
This PR moves the handling of players, enemies, maps and physics engine to a _GameState_ class in the new _my_helpers.py_ file.
> Add class GameState

- my_game.py
- my_helpers.py
Adding emitters to enemy deaths.
> GORE EFFECTS 🩸☠️

- my_game.py
- my_helpers.py
- my_sprites.py
weapons have a new data property: knockback
This determines how much the weapons push sprites that get hit backwards
> added knock_back to weapons

- my_game.py
- my_helpers.py
- Changed some parameters in the death emitter gore effect.
- Added some HP to the enemy from 5 to 14
> Enemy health up + Gore update

- my_game.py
- When the player drops below 1 it will switch to the screen GAME OVER!
> Added GAME OVER when player dies. 💀

- my_game.py
- my_sprites.py
health is now only visible for a short period of time when either the enemy or player is hit
> Life bar only on hit
